name: build_tools
version: 0.0.6
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Build tools is a build automation tool with a built-in command line shell.
homepage: https://github.com/mezoni/build_tools
dependencies:
  args: any
  file_utils: any
  globbing: any
  logging: any
  patsubst:
    git: https://github.com/mezoni/patsubst.git
